<?php
/*
part of PWision toolkit: http://pwision.googlecode.com/
Copyright (C) 2012 Becheru Petru-Ioan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

include_once("sections/pwision/pwision_MySettings.inc");


/** 	The MySettings class is designed to model the section that allows a user to configure its account.
	*	\latexonly \label{PWision:Sections:MySettings} \index{MySettings} \endlatexonly
	*	\brief a user editor.
	*	\version 2.0.0
	*/
class MySettings extends pwision_MySettings
	{
	}
?>