<?php
/*
part of PWision toolkit: http://pwision.googlecode.com/
Copyright (C) 2009,2010 Becheru Petru-Ioan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/**	\file
	*	\brief pwision translation to romanian.
	*	\version 1.1.1
	*/

// PCSSZenWebPage
PMainComponent::$Lang['Bookmarks']='Acces Rapid';
PMainComponent::$Lang['Website\'s sections']='Sect&#x0326;iunile Principale';
PMainComponent::$Lang['Subsections of']='Subsect&#x0326;iunile din';

/// PWision's sections

PMainComponent::$Lang['Parammeter']='Parametrul';
PMainComponent::$Lang['has an illegal value!']='are o valoare nepermisa!';
PMainComponent::$Lang['is not set!']='nu este setat!';

PMainComponent::$Lang['subsection found']='subsect&#x0326;iune g&#259;sit&#259;';
PMainComponent::$Lang['subsections found']='subsect&#x0326;iuni g&#259;site';


PMainComponent::$Lang['Root']='Prima pagin&#259;';
	PMainComponent::$Lang['Input section was not accessible. Root section loaded instead!']='Sect&#x0326;iunea data nu a fost accesibila. Sect&#x0326;iunea Root a fost incarcata!';
PMainComponent::$Lang['login']='Conectare';
	PMainComponent::$Lang['Login a user']='Conecteaz&#259; un utilizator';
	PMainComponent::$Lang['Please identify']='Identificare';
	PMainComponent::$Lang['Log in!']='Logheaz&#259;-te!';
PMainComponent::$Lang['UserAccess']='Access Utilizatori';

	PMainComponent::$Lang['You are now being redirected to section']='Redirectare c&#259;tre sect&#x0326;iunea';
	PMainComponent::$Lang['You are now being redirected to']='Redirectare c&#259;tre';

PMainComponent::$Lang['']='';
?>