<?php
/*
part of PWision toolkit: http://pwision.googlecode.com/
Copyright (C) 2009--11 Becheru Petru-Ioan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/**	\file
	*	\brief pwision translation to romanian.
	*	\version 1.3.2
	*/


PMainComponent::$Lang['Select a layout for the virtual keyboard']='Selecteaz&#259; limba tastaturii virtuale';
PMainComponent::$Lang['Insert:']='Insereaz&#259;:';

// PCSSZenWebPage
PMainComponent::$Lang['Bookmarks']='Acces Rapid';
PMainComponent::$Lang['Website\'s sections']='Secțiuni';
PMainComponent::$Lang['Subsections of']='Subsecțiunile din';

/// PWision's sections

PMainComponent::$Lang['Parammeter']='Parametrul';
PMainComponent::$Lang['has an illegal value!']='are o valoare nepermisa!';
PMainComponent::$Lang['is not set!']='nu este setat!';

PMainComponent::$Lang['subsection found']='subsecțiune g&#259;sit&#259;';
PMainComponent::$Lang['subsections found']='subsecțiuni g&#259;site';


PMainComponent::$Lang['Root']='Prima pagin&#259;';
	PMainComponent::$Lang['Input section was not accessible. Root section loaded instead!']='Secțiunea data nu a fost accesibila. Secțiunea Root a fost incarcata!';
PMainComponent::$Lang['login']='Conectare';
	PMainComponent::$Lang['Login a user']='Conecteaz&#259; un utilizator';
	PMainComponent::$Lang['Please identify']='Identificare';
	PMainComponent::$Lang['Log in!']='Logheaz&#259;-te!';
PMainComponent::$Lang['UserAccess']='Access Utilizatori';

	PMainComponent::$Lang['You are now being redirected to section']='Redirectare c&#259;tre secțiunea';
	PMainComponent::$Lang['You are now being redirected to']='Redirectare c&#259;tre';

PMainComponent::$Lang['']='';
?>