 <?php
// PCSSZenWebPage
PMainComponent::$Lang['Bookmarks']='Acces Rapid';
PMainComponent::$Lang['Website\'s sections']='Sec&#x21B;iunile Principale';
PMainComponent::$Lang['Subsections of']='Subsec&#x21B;iunile din';
 
/// PWision's sections
PMainComponent::$Lang['Root']='Prima pagin&#259;';
PMainComponent::$Lang['login']='Conectare';
	PMainComponent::$Lang['Login a user']='Conecteaz&#259; un utilizator';
	PMainComponent::$Lang['Please identify']='Identificare';
	PMainComponent::$Lang['Log in!']='Logheaz&#259;-te!';
PMainComponent::$Lang['UserAccess']='Access Utilizatori';

PMainComponent::$Lang['']='';
?>